import { Providers } from "../provider";
import localFont from "next/font/local";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pasito = localFont({
  src: "./fonts/El-Pasito-Light.otf",
  variable: "--font-pasito",
  display: "swap",
});

const guida = localFont({
  src: "./fonts/Guida.ttf",
  variable: "--font-Guida",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${pasito.variable} ${guida.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
